import localFont from "next/font/local";
import "@styles/globals.css";
import Nav from "@components/Nav";
import Footer from "@components/Footer";

export const metadata = {
  title: "TechStore",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='h-[100vh] flex flex-col'>
        <Nav></Nav>
        <div className='grow'>{children}</div>
        <Footer></Footer>
      </body>
    </html>
  );
}
