import localFont from "next/font/local";
import "@styles/globals.css";
import Nav from "@components/UI/Nav";
import Footer from "@components/UI/Footer";

import { config, icon } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";
import SupportChatBox from "@components/Chat/SupportChatBox";
config.autoAddCss = false;

export const metadata = {
  title: process.env.NEXT_PUBLIC_APP_NAME,
  description: "Generated by create next app",
  icons: {
    icon: process.env.NEXT_PUBLIC_APP_LOGO, // Ensure this path is correct
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="min-h-[100vh] flex flex-col">
        <Nav></Nav>
        <div className="grow h-fit flex justify-center">
          <div className="max-w-[1200px] w-full px-2 py-4">{children}</div>
        </div>
        <Footer></Footer>
        <SupportChatBox/>
      </body>
    </html>
  );
}
