export enum ORDER_STATUS {
  PENDING = 'PENDING',
  CONFIRMED = 'CONFIRMED',
  SHIPPED = 'SHIPPED',
  DELIVERED = 'DELIVERED',
  CANCELLED = 'CANCELLED'
}
export enum EMPLOY_STATUS {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  SUSPENDED = 'SUSPENDED',
  RESIGNED = 'RESIGNED'
}

export enum PAYMENT_METHOD {
  COD = 'COD',
  ELECTRO_WALLET = 'ELECTRO_WALLET',
  CREDIT_CARD = 'CREDIT_CARD',
}